### ISSUE TITLE
AttributeError: 'int' object has no attribute 'isdigit'

### ISSUE THREAD

**Issue by sugamkarki** [pelmers/Matmini#1]
```
Traceback (most recent call last):
  File "D:\NAMI\Year-3\MT CSY3010\Term II\reexam\Matmini\matmini.py", line 270, in <module>
    main(sys.argv)
  File "D:\NAMI\Year-3\MT CSY3010\Term II\reexam\Matmini\matmini.py", line 256, in main
    length = int(length) if length.isdigit() else 1
AttributeError: 'int' object has no attribute 'isdigit'
```
Is this  a python version issue?

**Comment by pelmers** [comment]
It's been a while since I ran this, but it expects the "-l" option to be passed with a space then number after it.
For example "-l 4". This sets the variable length to 4.  
 
 
  On Mon, Feb 28, 2022 at 15:19, Sugam ***@***.***> wrote:   

Traceback (most recent call last):
  File "D:\NAMI\Year-3\MT CSY3010\Term II\reexam\Matmini\matmini.py", line 270, in <module>
    main(sys.argv)
  File "D:\NAMI\Year-3\MT CSY3010\Term II\reexam\Matmini\matmini.py", line 256, in main
    length = int(length) if length.isdigit() else 1
AttributeError: 'int' object has no attribute 'isdigit'

Is this a python version issue?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
